# Generated by Django 3.2.12 on 2022-06-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoo', '0002_auto_20220626_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_complete',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
