# Generated by Django 3.2.12 on 2022-06-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoo', '0003_alter_todo_date_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='memo',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
