# Generated by Django 3.2.12 on 2022-07-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoo', '0006_auto_20220630_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='complete',
            field=models.DateField(blank=True),
        ),
    ]
